import { Type } from "class-transformer";
import { ApiProperty, ApiPropertyOptional } from "@nestjs/swagger";
import {
  IsArray,
  IsDateString,
  IsInt,
  IsOptional,
  IsString,
  MaxLength,
  Min,
  ValidateNested
} from "class-validator";
import { AddTripStaffDto } from "./trip-staff.dto.js";

export class CreateTripDto {
  @ApiPropertyOptional({ description: "Generated by the server when omitted" })
  @IsOptional()
  @IsString()
  @MaxLength(80)
  tripNumber?: string;

  @ApiPropertyOptional({ type: "integer", format: "int64", nullable: true })
  @IsOptional()
  @IsInt()
  @Min(1)
  routeId?: number | null;

  @ApiProperty({ example: "2026-09-01" })
  @IsDateString({ strict: true })
  tripDate!: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  @MaxLength(30)
  shiftCode?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsInt()
  @Min(1)
  vehicleId?: number;

  @ApiPropertyOptional()
  @IsOptional()
  @IsInt()
  @Min(1)
  primaryStaffId?: number;

  @ApiPropertyOptional()
  @IsOptional()
  @IsDateString()
  plannedStartAt?: string;

  @ApiPropertyOptional({ type: [AddTripStaffDto] })
  @IsOptional()
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => AddTripStaffDto)
  staff?: AddTripStaffDto[];
}
